### ISSUE TITLE
Scheduler not loading in production build

### ISSUE THREAD

**Issue by gpsfl** [stefanuebe/vaadin-fullcalendar#190]
### Bug Description

A calendar with scheduler active doesn't load in productions builds. It works using the dev server.

The same code has worked with version vaadin-fullcalendar 4.x, but after ugprading to 6.x it doesn't work anymore.

There are no warnings/errors in javascript console or in the server log. 

Vaadin version 24

Dev:
![image](https://github.com/stefanuebe/vaadin-fullcalendar/assets/38128299/8f5c34dd-f4a9-4559-af7e-d5cad10c1419)

Production:
![image](https://github.com/stefanuebe/vaadin-fullcalendar/assets/38128299/a0e037ab-ce03-4ce8-9b79-846283b8c0a1)

### Example Code

```
FullCalendar calendar = FullCalendarBuilder.create().withScheduler().build();

((Scheduler) calendar).setSchedulerLicenseKey("GPL-My-Project-Is-Open-Source"); // Use GPL key for testing, we also have a license key

calendar.setSizeFull();
calendar.changeView(RESOURCE_TIMELINE_DAY);

add(calendar); // Add to some layout
```

**Comment by stefanuebe** [comment]
I tried to reproduce the issue, but it works for me (as also can be seen in the demo, which runs in production mode). 

Have you added the addon packages to the package whitelist? https://github.com/stefanuebe/vaadin-fullcalendar/wiki/FAQ

**Comment by stefanuebe** [comment]
I tried to reproduce your issue, but it works for me. Since the demo also works, I assume it might be something with your project setup or configuration.

This is my result when adding your snippet to my demo as a new, empty view (using a vertical layout). 

<img width="611" alt="image" src="https://github.com/stefanuebe/vaadin-fullcalendar/assets/36725474/8c3927b2-2daf-4728-886f-2b207d40d3a1">

Two things to check / try:
1. Please check, that the addon package is added to the whitelist package, if you use a Spring project. https://github.com/stefanuebe/vaadin-fullcalendar/wiki/FAQ
2. Maybe the component is referenced indirectly and the package scanner cannot determine the usage of your component and thus the FC and simply strips the respective scripts from the packages. In that case I would expect error messages, but just to be sure, you could add a `@Uses(FullCalendarScheduler.class)` to you AppShellConfigurator or main router layout. This should then make Vaadin also scan and include the addon classes.

**Comment by gpsfl** [comment]
We aren't using spring, it's a plain old java servlet web app with maven. 

Adding `@Uses(FullCalendarScheduler.class)` fixed it for me
